/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author Miguel Culma
 */
public class Funciones_Logicas extends javax.swing.JFrame {

    public Funciones_Logicas() {

        centrarVentana();
        initComponents();

    }
    

    public void centrarVentana() {

        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        int x = (screenSize.width - frameSize.width) / 20;
        int y = (screenSize.height - frameSize.height) / 20;
        setLocation(x, y);

    }

    public JTextField getTxtbusqueda() {
        return txtbusqueda;
    }

    public JButton getBnt_busqueda() {
        return bnt_busqueda;
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        spn_nVariables = new javax.swing.JSpinner();
        btn_generarTabla = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txt_operacion = new javax.swing.JTextField();
        btnsimplificar = new javax.swing.JButton();
        btn_refrescar = new javax.swing.JButton();
        btn_suma = new javax.swing.JButton();
        btn_producto = new javax.swing.JButton();
        btn_negacion = new javax.swing.JButton();
        bnt_busqueda = new javax.swing.JButton();
        btn_xor = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtbusqueda = new javax.swing.JTextField();
        btn_xnor1 = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Funciones Lógicas");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        spn_nVariables.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        spn_nVariables.setModel(new javax.swing.SpinnerNumberModel(1, 1, 26, 1));
        spn_nVariables.setToolTipText("");
        spn_nVariables.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(spn_nVariables, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 290, 25));

        btn_generarTabla.setBackground(new java.awt.Color(86, 84, 84));
        btn_generarTabla.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_generarTabla.setForeground(new java.awt.Color(255, 255, 255));
        btn_generarTabla.setText("Generar Tabla");
        btn_generarTabla.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(86, 84, 84), 1, true));
        jPanel1.add(btn_generarTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 140, 40));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("FUNCIONES LÓGICAS");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 280, 37));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cantidad Variables:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 500, 10));

        txt_operacion.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txt_operacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_operacion.setToolTipText("Para realizar una operación, separe los argumentos con una coma y seleccione la operación");
        txt_operacion.setBorder(new javax.swing.border.MatteBorder(null));
        txt_operacion.setOpaque(true);
        jPanel1.add(txt_operacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 290, 25));

        btnsimplificar.setBackground(new java.awt.Color(86, 84, 84));
        btnsimplificar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnsimplificar.setForeground(new java.awt.Color(255, 255, 255));
        btnsimplificar.setText("Simplificar");
        btnsimplificar.setBorder(null);
        jPanel1.add(btnsimplificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, 100, 40));

        btn_refrescar.setBackground(new java.awt.Color(86, 84, 84));
        btn_refrescar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_refrescar.setForeground(new java.awt.Color(255, 255, 255));
        btn_refrescar.setText("Refrescar");
        btn_refrescar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(86, 84, 84), 1, true));
        btn_refrescar.setBorderPainted(false);
        jPanel1.add(btn_refrescar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, 110, 40));

        btn_suma.setBackground(new java.awt.Color(86, 84, 84));
        btn_suma.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_suma.setForeground(new java.awt.Color(255, 255, 255));
        btn_suma.setText("Suma");
        btn_suma.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(86, 84, 84), 1, true));
        jPanel1.add(btn_suma, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 100, 40));

        btn_producto.setBackground(new java.awt.Color(86, 84, 84));
        btn_producto.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_producto.setForeground(new java.awt.Color(255, 255, 255));
        btn_producto.setText("Producto");
        btn_producto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(86, 84, 84), 1, true));
        jPanel1.add(btn_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 100, 40));

        btn_negacion.setBackground(new java.awt.Color(86, 84, 84));
        btn_negacion.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_negacion.setForeground(new java.awt.Color(255, 255, 255));
        btn_negacion.setText("Negación");
        btn_negacion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(86, 84, 84), 1, true));
        jPanel1.add(btn_negacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, 100, 40));

        bnt_busqueda.setBackground(new java.awt.Color(86, 84, 84));
        bnt_busqueda.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        bnt_busqueda.setForeground(new java.awt.Color(255, 255, 255));
        bnt_busqueda.setText("Buscar");
        bnt_busqueda.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(86, 84, 84), 1, true));
        jPanel1.add(bnt_busqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, 100, 40));

        btn_xor.setBackground(new java.awt.Color(86, 84, 84));
        btn_xor.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_xor.setForeground(new java.awt.Color(255, 255, 255));
        btn_xor.setText("XOR");
        btn_xor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(86, 84, 84), 1, true));
        jPanel1.add(btn_xor, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 310, 100, 40));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Ingrese los valores a consultar:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Ingrese Operación:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        txtbusqueda.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtbusqueda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtbusqueda.setToolTipText("Ingrese los valores a consultar separados por un espacio");
        txtbusqueda.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(txtbusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 240, 25));

        btn_xnor1.setBackground(new java.awt.Color(86, 84, 84));
        btn_xnor1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_xnor1.setForeground(new java.awt.Color(255, 255, 255));
        btn_xnor1.setText("XNOR");
        btn_xnor1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(86, 84, 84), 1, true));
        jPanel1.add(btn_xnor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, 100, 40));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Fondo.jpg"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    public javax.swing.JButton bnt_busqueda;
    public javax.swing.JButton btn_generarTabla;
    public javax.swing.JButton btn_negacion;
    public javax.swing.JButton btn_producto;
    public javax.swing.JButton btn_refrescar;
    public javax.swing.JButton btn_suma;
    public javax.swing.JButton btn_xnor1;
    public javax.swing.JButton btn_xor;
    public javax.swing.JButton btnsimplificar;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JSpinner spn_nVariables;
    public javax.swing.JTextField txt_operacion;
    public javax.swing.JTextField txtbusqueda;
    // End of variables declaration//GEN-END:variables
}
